# Generated by Django 5.2.7 on 2025-11-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('gamer', 'Gamer'), ('dev', 'Developer')], default='developer', max_length=5),
        ),
    ]
