# Generated by Django 5.2.7 on 2025-11-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_site', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whitelisted_games',
            field=models.ManyToManyField(blank=True, help_text='Games this user has marked as ‘whitelisted’ (favorite).', related_name='whitelisted_by', to='game_site.game'),
        ),
    ]
